
language: ruby

cache: bundler

branches:
  only:
    - master

script: 
  - bundle exec jekyll algolia push
  - bundle exec jekyll build 
  - bundle exec htmlproofer ./_site --disable-external --empty-alt-ignore

rvm:
 - 2.2.2
 