
# Site settings
post-preview-words: 350

# Related posts settings
minimum-tags-difference: 1
maximum-related-posts: 3
# Available values: lt, gt
related-date-condition: lt

# Pagination settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: none
plugins: 
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia

# Search funcionality
algolia:
  application_id: 2HS4H6WLCZ
  index_name: prod_way-of-the-developer
  search_only_api_key: 96f66a5d1fb9249100d1c6312f76bfcb
  files_to_exclude:
    - index.html
    - 404.html
    - search.md
    - donation.md
    - blog
    - docs
    - assets

exclude: 
  - vendor
  - Gemfile
  - Gemfile.lock
  - _scripts
  - _excludes
