
title: Way of the Developer
tagline: how to I become a developer

# Authors documented under _data

# GitHub related
github-repository: gfarfanb.github.io
github-branch: master

# Assets root
assets: https://raw.githubusercontent.com/wiki/gfarfanb/gfarfanb.github.io

# Change to true for Disqus comments
disqus:
  comments: true
  disqus-shortname: way-of-the-developer

# Google Analytics
google-tracking-id: UA-34247146-3

# Donations with PayPal
donate-paypal: KXJRZY6D3Z29E
# Donations with BitCoins
donate-blockchain: 1P4w32KT7NwjfGLmnr1eeWs2xJs468PKSk

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Blog', leafs: [
    {name: 'Tags', url: 'blog/tag.html'}, 
    {name: 'Categories', url: 'blog/category.html'},
    {name: 'Archive', url: 'blog/archive.html'}
  ]}
- {name: 'Contact', url: 'contact.html'}

# http://fontawesome.io/icons/ - Brand Icons
social:
- {icon: 'github', link: 'https://github.com/', head: true}
- {icon: 'twitter', link: 'https://twitter.com/', head: true}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/', head: false}
- {icon: 'envelope', link: 'mailto:', head: true}
